version: '3.1'

services:

  db:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'

    environment:
      MYSQL_DATABASE: 'example'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'school-admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mysql'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql'