version: '3.1'

services:
  rest-school-api:
    container_name: rest-school
    image: "rest-school-api"
    build: rest-school/
    ports:
    - "8081:8081"
    depends_on:
    - mysqldb

  mysqldb:
    container_name: mysqldb-container
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'example'
      MYSQL_USER: 'adminschool'
      MYSQL_PASSWORD: 'adminschool'
      # So you don't have to use root, but you can if you like
      # You can use whatever password you like
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql'
# Names our volume
volumes:
  mysqldb:
