CREATE TABLE STUDENT (
  id BIGINT AUTO_INCREMENT NOT NULL,
   name VARCHAR(255),
   surname VARCHAR(255),
   age VARCHAR(255),
   phone_number VARCHAR(255),
   CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE TEACHER (
  id BIGINT AUTO_INCREMENT NOT NULL,
   name VARCHAR(255),
   surname VARCHAR(255),
   subject VARCHAR(255),
   CONSTRAINT pk_teacher PRIMARY KEY (id)
);


